### ISSUE TITLE
Swift 3.0 Support?

### ISSUE THREAD

**Issue by dahikarShashant** [drichardson/SwiftyBase64#2]
Hi, Any plans of updating this to swift 3.0. Thanks in advance!

**Comment by drichardson** [comment]
Yes, I actually merged in #1 to address this, but then realized that PR was incorrect so had to revert. I will try to take a stab at this sometime this week.

**Comment by dpopov** [comment]
Just submitted a pull request that addresses this

**Comment by drichardson** [comment]
Fixed as of 248b99ce3580ac2808e. Pushing to cocoapods now.

**Comment by drichardson** [comment]
And thanks again @dpopov!

**Comment by dahikarShashant** [comment]
Thankyou so much! You are awesome! :)
